Repository KhangLeonardo/capstone-app-server, pull requests merged in 2024-06, with the labels that each got.

#38 Be/write-controller-service-for-schedule-api ( Check pull request and merge #37 first before this PR)
  .github/workflows/ci-lint.yml
  eslint_report.json
  src/api/absence/absence.controller.ts
  src/api/absence/absence.service.ts
  src/api/absence/dto/create-absence.dto.ts
  src/api/attendance/attendace.controller.spec.ts
  src/api/attendance/attendace.controller.ts
  src/api/attendance/attendace.module.ts
  src/api/attendance/attendace.service.spec.ts
  src/api/attendance/attendace.service.ts
  src/api/attendance/attendance.controller.ts
  src/api/attendance/attendance.module.ts
  src/api/attendance/attendance.service.ts
  src/api/attendance/dto/create-attendance.dto.ts
  src/api/attendance/dto/update-attendace.dto.ts
  src/api/attendance/dto/update-attendance.dto.ts
  src/api/class/class.controller.ts
  src/api/class/class.service.ts
  src/api/classroom-type/classroom-type.controller.ts
  src/api/classroom-type/classroom-type.service.ts
  src/api/classroom/classroom.controller.ts
  src/api/classroom/classroom.service.ts
  src/api/daily-schedule/daily-schedule.controller.ts
  src/api/daily-schedule/daily-schedule.service.ts
  src/api/daily-schedule/dto/create-daily-schedule.dto.ts
  src/api/event/event.controller.ts
  src/api/event/event.service.ts
  src/api/meal/meal.controller.ts
  src/api/meal/meal.service.ts
  src/api/menu-category/menu-category.controller.ts
  src/api/menu-category/menu-category.service.ts
  src/api/menu/menu.controller.ts
  src/api/menu/menu.service.ts
  src/api/parent/parent.controller.ts
  src/api/parent/parent.service.ts
  src/api/period/period.controller.ts
  src/api/period/period.service.ts
  src/api/school-year/school-year.controller.ts
  src/api/school-year/school-year.service.ts
  src/api/student-class/student-class.controller.ts
  src/api/student-class/student-class.service.ts
  src/api/student-parent/student-parent.controller.ts
  src/api/student-parent/student-parent.service.ts
  src/api/student-year-level/student-year-level.controller.ts
  src/api/student-year-level/student-year-level.service.ts
  src/api/student/student.controller.ts
  src/api/student/student.service.ts
  src/api/subject/subject.controller.ts
  src/api/subject/subject.service.ts
  src/api/teacher/teacher.controller.ts
  src/api/teacher/teacher.service.ts
  src/api/term/term.controller.ts
  src/api/term/term.service.ts
  src/api/year-level/year-level.controller.ts
  src/api/year-level/year-level.service.ts
  src/app.module.ts
  src/common/entities/daily-schedule.entity.ts
Labels: performance

#39 config migration for app
  db/data-source.ts
  db/migrations/1718955771360-NewMigration.ts
  package-lock.json
  package.json
  src/providers/database/postgres/postgres.module.ts
Labels: enhancement, performance

#50 Be/schedule
  schema/init.sql
  src/api/class_schedule/class_schedule.controller.ts
  src/api/class_schedule/class_schedule.module.ts
  src/api/class_schedule/class_schedule.service.ts
  src/api/class_schedule/dto/create-class_schedule.dto.ts
  src/api/class_schedule/dto/update-class_schedule.dto.ts
  src/api/eating_schedule/dto/create-eating_schedule.dto.ts
  src/api/eating_schedule/dto/update-eating_schedule.dto.ts
  src/api/eating_schedule/eating_schedule.controller.ts
  src/api/eating_schedule/eating_schedule.module.ts
  src/api/eating_schedule/eating_schedule.service.ts
  src/app.module.ts
  src/common/entities/daily-schedule.entity.ts
  src/common/entities/eating-schedule.entity.ts
  src/migrations/seedings/seedings.controller.spec.ts
  src/migrations/seedings/seedings.controller.ts
  src/migrations/seedings/seedings.module.ts
  src/migrations/seedings/seedings.service.spec.ts
  src/migrations/seedings/seedings.service.ts
Labels: enhancement
