Repository KhangLeonardo/capstone-app-server, pull requests merged in 2024-04, with the labels that each got.

#2 Update README.md
  README.md
Labels: help wanted

#3 Update README.md
  README.md
Labels: bug

#1 init
  .dockerignore
  .eslintrc.js
  .github/workflows/merge.yml
  .gitignore
  .prettierrc
  Dockerfile
  README.md
  docker-compose.yaml
  nest-cli.json
  nginx.conf
  package-lock.json
  package.json
  scripts/setup.sh
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: documentation, enhancement, good first issue

#5 add CODEOWNER
  .github/CODEOWNDER
Labels: help wanted

#7 move CODEOWNER
  .github/CODEOWNDER
  CODEOWNDER
Labels: help wanted

#10 feature/db-connection
  .dockerignore
  .github/workflows/merge.yml
  .github/workflows/merge_restriction.yml
  .gitignore
  Dockerfile
  docker-compose.yaml
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/database/database.module.ts
Labels: enhancement, help wanted, good first issue, breaking change

#11 update-20240421
  .github/workflows/merge_restriction.yml
Labels: security

#12 update-20240422-02:10AM
  .dockerignore
  Dockerfile
  README.md
  database/init.sql
  docker-compose.yaml
  nginx.conf
  package-lock.json
  package.json
  scripts/setup.sh
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/create-auth.dto.ts
  src/auth/dto/update-auth.dto.ts
  src/auth/entities/auth.entity.ts
  src/database/database.module.ts
  src/main.ts
  src/server/server.controller.spec.ts
  src/server/server.controller.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/entities/user.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: enhancement, performance, test

#14 do logout and profile function
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: enhancement

#15 feature/auth-api-refactor
  .env.example
  docker-compose.yaml
  nginx.conf
  schema/init.sql
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/entities/user-session.entity.ts
  src/auth/jwt.strategy.ts
Labels: enhancement, help wanted, refactor

#16 addd file yaml
  .eslintignore
  .eslintrc.json
  .github/workflows/ci-be.yml
  eslint_report.json
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: performance

#18 Adding JWT Strategy to fix the jwt not found error
  docker-compose.yaml
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/interfaces/jwt-payload.interface.ts
  src/auth/jwt.strategy.ts
Labels: bug, enhancement, refactor
